name: container-build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  # Best practice to hard-code your GitHub username below in LOWERCASE.
  # Update to your own GitHub username.
  IMAGE_NAME: jac7az/fastapi-demo--c
  IMAGE_TAG: 1.${{ github.run_number }} # GITHUB_RUN_NUMBER
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
